namespace Akka.Mix.Messages; 

// partial message definitions are generated by the protobuf compiler
// we can extend them with our own code here

public partial class CountReport
{
    public static readonly string ProcessorName = "count-report-processor";
    public static readonly string ProcessorPath = $"/user/{ProcessorName}";

    public static readonly string Topic = "count-reports-topic";
} 
